import serial
from time import sleep

# Identify ATmega32 port and baudrate
transmitter_location = serial.Serial(port="/dev/serial0", baudrate=9600)
sleep(0.05)
count = 0
while True:
  print("**** ", count, " ****")
  count += 1
  transmitter_location.write(str.encode('S'))
  sleep(5)
  transmitter_location.write(str.encode('A'))
  print("Forward")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('B'))
  print("Backward")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('R'))
  print("Rotate Right")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('L'))
  print("Rotate Left")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('Y'))
  print("Forward Right")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('E'))
  print("Forward Left")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('Q'))
  print("Backward Right")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  sleep(1)
  transmitter_location.write(str.encode('W'))
  print("Backward Left")
  sleep(5)
  transmitter_location.write(str.encode('S'))
  print("Stop")
  sleep(5)
  print("\n\n\n\n\n")
